apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepika-pv
  namespace: demo
  labels:
    type: deepika-pv
spec:
  claimRef:
    name: deepika-pvc
    namespace: demo
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/redis
