apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepika-pvc
  namespace: demo
  labels:
      type: deepika-pvc
spec:
  volumeName: deepika-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
